# Generated by Django 5.1.2 on 2024-11-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='Foto',
        ),
        migrations.AddField(
            model_name='personas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
