# Generated by Django 5.1.2 on 2024-11-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_productos_delete_crearproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
