# Generated by Django 5.1.2 on 2024-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_rename_nacimiento_personas_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
